public class AccountDanger implements Runnable{
	private Account acct = new Account();
	public static void main (String args[]){
		AccountDanger r= new AccountDanger();
		Thread one = new Thread(r);
		Thread two = new Thread(r);
		one.setName("Fred");
		two.setName("Lucy");
		one.start();
		two.start();		
	}
	public void run(){
		for (int x=0; x<5; x++){
			makeWithdrawal(10);
			if (acct.getBalance()<0){
				System.out.println("Account is overdrawn!");
			}
		}
	}
	private synchronized void makeWithdrawal (int amt){
		if (acct.getBalance()>=amt){
			System.out.println(Thread.currentThread().getName()+" is going to withdraw...");
			try{
				Thread.sleep(500);
			}
			catch(InterruptedException ex){}
			acct.withdraw(amt);
			System.out.println(Thread.currentThread().getName()+" completes the withdrawal...");
		}
		else{
			System.out.println("Not enough money in account for "+Thread.currentThread().getName()+ " to withdraw:  "+ acct.getBalance());
		}
		
	}
}

class Account {
	private int balance=70;
	public int getBalance(){ return balance;}
	public void withdraw (int amt){
		balance=balance-amt;
	}
}

/*
Without synchronized:
Fred is going to withdraw...
Lucy is going to withdraw...
Fred completes the withdrawal...
Fred is going to withdraw...
Lucy completes the withdrawal...
Lucy is going to withdraw...
Fred completes the withdrawal...
Fred is going to withdraw...
Lucy completes the withdrawal...
Lucy is going to withdraw...
Fred completes the withdrawal...
Lucy completes the withdrawal...
Fred is going to withdraw...
Lucy is going to withdraw...
Fred completes the withdrawal...
Account is overdrawn!
Lucy completes the withdrawal...
Account is overdrawn!
Not enough money in account for Fred to withdraw:  -10
Account is overdrawn!
Not enough money in account for Lucy to withdraw:  -10
Account is overdrawn!



Lucy is going to withdraw...
Fred is going to withdraw...
Lucy completes the withdrawal...
Lucy is going to withdraw...
Fred completes the withdrawal...
Fred is going to withdraw...
Lucy completes the withdrawal...
Lucy is going to withdraw...
Fred completes the withdrawal...
Fred is going to withdraw...
Lucy completes the withdrawal...
Lucy is going to withdraw...
Fred completes the withdrawal...
Fred is going to withdraw...
Lucy completes the withdrawal...
Fred completes the withdrawal...
Account is overdrawn!
Not enough money in account for Fred to withdraw:  -10
Account is overdrawn!
Not enough money in account for Lucy to withdraw:  0
Account is overdrawn!

With synchronized:
Fred is going to withdraw...
Fred completes the withdrawal...
Fred is going to withdraw...
Fred completes the withdrawal...
Fred is going to withdraw...
Fred completes the withdrawal...
Fred is going to withdraw...
Fred completes the withdrawal...
Fred is going to withdraw...
Fred completes the withdrawal...
Lucy is going to withdraw...
Lucy completes the withdrawal...
Lucy is going to withdraw...
Lucy completes the withdrawal...
Not enough money in account for Lucy to withdraw:  0
Not enough money in account for Lucy to withdraw:  0
Not enough money in account for Lucy to withdraw:  0


*/

